### PR TITLE
raise error when R / knitr not accessible

### LINKED ISSUE #18: raise error if knitr not installed
Using --knit fails silently if knitr is not installed - the result is an empty notebook.

Ideally an error would be raised instead.

### PR DESCRIPTION
**Pull request by aaren**
fixes #18.

@jni can you test this out? (I'm assuming that you still don't have knitr installed).

### CODE REVIEW

**Comment by jni** [comment]
Gah! Not quite, on Python 3:

```console
 ~/projects/notedown ((detached from upstream/r-error))$ python -m nose tests.py..........E
======================================================================
ERROR: Check that the R notebook generated from Rmd looks the same
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/envs/elegant/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Volumes/Projects/notedown/tests.py", line 346, in test_R
    knitr = notedown.Knitr()
  File "/Volumes/Projects/notedown/notedown/notedown.py", line 544, in __init__
    if 'not found' in stderr:
TypeError: 'str' does not support the buffer interface
```

**Comment by aaren** [comment]
Should work now?

**Comment by jni** [comment]
Yep, perfect!

```
 ~/projects/notedown ((detached from upstream/r-error))$ python -m nose tests.py 
..........E
======================================================================
ERROR: Check that the R notebook generated from Rmd looks the same
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/envs/elegant/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Volumes/Projects/notedown/tests.py", line 346, in test_R
    knitr = notedown.Knitr()
  File "/Volumes/Projects/notedown/notedown/notedown.py", line 555, in __init__
    raise self.KnitrError(message)
notedown.notedown.KnitrError: Could not load knitr (needs manual installation).

$ ['Rscript', '-e', 'require(knitr)']
Loading required package: knitr
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘knitr’


----------------------------------------------------------------------
Ran 11 tests in 0.477s

FAILED (errors=1)
```

**Comment by aaren** [comment]
Great. Thanks for your help :)

**Comment by jni** [comment]
No worries! =)

On reflection I find this interaction amusing:

- option 1: painstakingly create a programming environment matching the failure you want to test.
- option 2: find a stranger on the other side of the planet who has that environment, and get them to run the test for you.

=P

**Pull request merged**
