### PR TITLE
jupyter support

### PR DESCRIPTION
**Pull request by aaren**
Work on supporting Jupyter and IPython 4.

The transition from IPython 3 to 4 was marked by the splitting of the monolithic IPython packages into a number of smaller packages (e.g. nbformat and nbconvert are now standalone).

There were a few import changes (which produced a warning if you used the old import path) and also some changes to the internals of nbconvert (the API of which I wasn't using properly). These have been addressed and this branch is now passing all tests.

However, this was done at the expense of IPython 3 compatibility (for ease of hacking). This shouldn't be hard to re-implement - I think it just needs import shims putting in.

TODO:

- [x] put in import shims to permit IPython 3
- [x] does nbconvert usage change from 3 to 4?

### CODE REVIEW

**Comment by aaren** [comment]
I think this is ready to go. Appears to be working just fine with ipython 3 & 4 on my machine.

Only problem is the requirements in setup.py, which aren't compatible with IPython 3. At this point I think it isn't unreasonable to expect an upgrade to IPython 4 / Jupyter.

**Comment by aaren** [comment]
closes #26

**Comment by lgautier** [comment]
> At this point I think it isn't unreasonable to expect an upgrade to IPython 4 / Jupyter.

I support this. If ipython < 4.0, the older version of `notedown` are available.

**Comment by aaren** [comment]
Current master should be all jupyter now. I've not made a release yet because I've been trying out upgrade edge cases. Will make one soon though. Is master working fine for you?

**Comment by lgautier** [comment]
Seems to be working. This is great ! Thanks.

This will let me build the notebook tutorials for the rpy2 doc (`.md -> .ipynb -> .rst =[sphinx]=> .html`) with jupyter-4.0.

**Pull request merged**
