### PR TITLE
Add Python 3 support

### PR DESCRIPTION
**Pull request by jni**
This PR brings nearly full compatibility for Python 3, while maintaining Python 2 compatibility.

The sole exception is the R-markdown test, which for me is failing on master as well. The failures on master and on this PR match.

### CODE REVIEW

**Comment by aaren** [comment]
Thanks for doing this :)

All tests are passing for me on master though. The R test does fail for me with this PR.

The knitr calling has always been a bit fragile so it might be something to do with that.

**Comment by jni** [comment]
Done! Let me know if this works! This still shows the same failure for me, but might be something weird with my R install. (It's a bit neglected these days!)

**Comment by aaren** [comment]
Thanks. Python 2 and 3 both passing for me now. 

The default for the temp files is `'w+b'`, which is the cause of the problem on
python 3.

Remaining things to do:

- [ ] update 442bbb as above (open tmp file as 'w+' and remove the 'rb' for
      the template file)

- [ ] squash all of the file IO commits together (the last two and 442bbb) -
      together I think they should amount to just setting `mode='w+'` for each 
      of the temp files.

- [ ] add `six` to the install_requires in setup.py


Re your failing R test: Does Knitr work for you from the command line? i.e. if
you run 

    notedown r-examples/r-example.Rmd --knit --to markdown

do you get sensible looking markdown? And if you run

    notedown r-examples/r-example.Rmd --knit --rmagic

is the result the same as `r-examples/r-example.ipynb`? (less the outputs,
which you can generate with `--run`)

**Comment by jni** [comment]
Hey @aaren, what do you mean "442bbb"? From context it sounds like you're talking about 37e4b25? There is no commit 442bbb in this history...

**Comment by jni** [comment]
Well, I'm assuming you meant 37e4b25, which I have now reverted and squashed in with all the knitr changes, as well as added six to the requirements, so we should be all good!

As to Knitr, no, not working. Here's my output to `notedown r-examples/r-example.Rmd --knit --rmagic`:

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext rpy2.ipython"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 0
}
```

The first command, `notedown r-examples/r-example.Rmd --knit --to markdown`, produces no output at all.

**Comment by aaren** [comment]
Merged. Thanks again for doing this.

Do you definitely have knitr installed? i.e. you don't get and error if you
start the R interpreter and then do `require(knitr)`?

**Comment by jni** [comment]
No worries! My workflow now depends on this and I really want to move to Python 3 full time so it's a very self-interested PR! =) Nonetheless, happy to help!

btw, do you think you might cut a release with this so I don't have to install from github? (not that it's a huge deal, just slightly less elegant.)

Finally, re: knitr, indeed I don't have it installed, so that explains a few things. =P It might be worth raising an error when knitr can't be found, rather than failing silently. But I'll leave that to you. I don't need knitr right now so I'm not worried about this!

**Comment by aaren** [comment]
Sorry, meant to do that already. I've just released notedown 1.4.0.

Yes, raising an error would be preferable. Have opened #18.

**Pull request merged**
