### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by scottsievert**
Issue #16 says unicode support doesn't exist, which is true. Turns out that the encoding of `open` and `stdout` has to be changed, using the `io` library (thank you Buck!).

This commit fixes that by changing `open` to `io.open(..., encoding='utf-8')` and the like.

### CODE REVIEW

**Comment by aaren** [comment]
Thanks Scott :)

aaf8ae isn't necessary. We don't need to add the pyc and egg-info to the
repository. Can you remove this commit?

**Comment by aaren** [comment]
I've merged your first commit. Thanks for doing this :)

**Comment by aaren** [comment]
This is now available on pypi as notedown 1.4.1

**Comment by scottsievert** [comment]
Perfect! I'll be shortly be releasing [rst-to-ipynb] on PyPI which depends on notedown.

[rst-to-ipynb]:https://github.com/scottsievert/rst-to-ipynb

**Pull request closed without merging**
